export default function InitialRelatorio(param) {

    let initial = {
        tempodoencaanos: '',
        tempodoencameses: '',
        vhs: '',
        pcr: '',
        pcrvn: '',
        ara: undefined,
        arb: undefined,
        arc: undefined,
        ard: undefined,
        are: undefined,
        arf: undefined,
        arg: undefined,
        eapa: undefined,
        eapb: undefined,
        eapc: undefined,
        eapd: undefined,
        eape: undefined,
        eapf: undefined,
        eapg: undefined,
        eaaa: undefined,
        eaab: undefined,
        eaac: undefined,
        eaad: undefined,
        eaae: undefined,
        medicamento1: '',
        dose1: '',
        inicio1: '',
        fim1: '',
        motivo1: '',
        medicamento2: '',
        dose2: '',
        inicio2: '',
        fim2: '',
        motivo2: '',
        medicamento3: '',
        dose3: '',
        inicio3: '',
        fim3: '',
        motivo3: '',
        medicamento4: '',
        dose4: '',
        inicio4: '',
        fim4: '',
        motivo4: '',
        medicamento5: '',
        dose5: '',
        inicio5: '',
        fim5: '',
        motivo5: '',
        medicamento6: '',
        dose6: '',
        inicio6: '',
        fim6: '',
        motivo6: '',
        medicamento7: '',
        dose7: '',
        inicio7: '',
        fim7: '',
        motivo7: '',
        ppddata: undefined,
        ppdresultado: '',
        rxtoraxdata: undefined,
        rxtoraxresultado: '',
        rxtoraxalteracao: '',
        bhcgdata: undefined,
        bhcgjustificativa: '',
        infeccaoviral: false,
        hepatite: false,
        infeccaobacteriana: false,
        neoplasia: false,
        anemia: false,
        alteracaohepatica: false,
        das28: '',
        cdai: '',
        sdai: '',
        basdai: '',
        asdas: '',
        sledai:'',
        essdai: '',
        mda: '',
        eva: '',
    }

    if (param) {
         initial = {...initial, lmeId: param}
    }

    return initial
}
